source 'https://rubygems.org'

gem 'jekyll', '3.8.6'

group :jekyll_plugins do
  gem 'jekyll-feed', '0.12.1'
  gem 'jekyll-seo-tag', '2.5.0'
  gem 'jekyll-sitemap', '1.2.0'
  gem 'jekyll-optional-front-matter', '0.3.0'
end
